import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import type { LiFiWidget } from '@lifi/widget';
import type { NextPage } from 'next';
import dynamic from 'next/dynamic';

const inter = Inter({ subsets: ['latin'] })
const LiFiWidgetDynamic = dynamic(
  () => import('@lifi/widget').then((module) => module.LiFiWidget) as any,
  {
    ssr: false,
  },
) as typeof LiFiWidget;
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LiFiWidgetDynamic
        config={{
          containerStyle: {
            width: 392,
            height: 640,
            border: `1px solid rgb(234, 234, 234)`,
            borderRadius: '16px',
            display: 'flex',
            maxWidth: 392,
          },
        }}
      />
    </>
  )
}
